version: '3.8'

services:
  app:
    image: golang:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
      - db-data:/app/data
    working_dir: /go/src/app
    command: go run main.go
    environment:
      - DB_PATH=/app/data/links.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data: